#!/bin/csh
clear
sum=0
i="y"
echo "enter first number"
read n
echo "enter sec number"
read m
while [ $i = "y" ]
do
echo "1.addition"
echo "2.subtraction"
echo "3.multiplication"
echo "4.division"
echo "enter your choice"
read ch
case $ch in 
1) sum=$(( $n + $m ))
echo "sum="$sum;;
2) sum=$(( $n - $m ))
echo "sub="$sum;; 
3) sum=$(( $n * $m ))
echo "mul="$sum;;
4) sum=$(( $n / $m ))
echo "div="$sum;;
*) echo "default no";;
esac
echo "do you want to continue"
read i
if [ $i != "y" ]
then
exit
fi
done
