#!/bin/csh
echo "enter 1st number"
read a
echo "enter 2nd number"
read b
echo "enter 3rd number"
read c
m=$(( ( $a + $b + $c) / 3 ))
p=`expr $a - $m`
q=`expr $b - $m`
r=`expr $c - $m`
d=$(( ( $p * $p + $q * $q + $r * $r) / 3 ))
w=`echo "sqrt( $d )" | bc -l`
echo " mean of $a $b $c is $m "
echo "standard deviation is $w "

