#!/bin/csh

echo "Enter the limit:"
set limit = $<

set n = 2

while ($n <= $limit)
    set i = 2
    set is_prime = 1

    while ($i * $i <= $n)
        if ($n % $i == 0) then
            set is_prime = 0
            break
        endif
        @ i++
    end

    if ($is_prime == 1) then
        echo $n
    endif

    @ n++
end
